Week2/ChefsNDishes/Models/Chef.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace ChefsNDishes.Models;

public class Chef
{
    [Key]
    public int ChefID {get; set;}

    [Required]
    [MinLength(2)]
    public string FirstName {get; set;}

    [Required]
    [MinLength(2)]
    public string LastName {get; set;}

    [Required(ErrorMessage="Chef's birthday is required")]
    [DateValidation(ErrorMessage="Chef must be over 18")]
    public DateTime BirthDate {get; set;}

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    public List<Dish> AllDishes {get; set;} = new List<Dish>();
}

public class DateValidation : ValidationAttribute
{
    public override bool IsValid(object value)
    {
        // check value is formatted correctly & in past
        if (value is DateTime BirthDate && BirthDate < DateTime.Now)
        {
            // find age
            int age = DateTime.Now.Year - BirthDate.Year;
            // check to see if they're over 18
            return age >= 18;
        }
        return false;
    }
}

Week2/ChefsNDishes/Models/Dish.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace ChefsNDishes.Models;

public class Dish
{
    [Key]
    public int DishID {get; set;}

    [Required]
    public string Name {get; set;}

    [Required]
    [Range(1, Int32.MaxValue, ErrorMessage = "Must have calories")]
    public int Calories {get; set;}

    [Required]
    [Range(1, 5)]
    public int Tastiness {get; set;}

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    // Now the part I still don't fully understand
    public int ChefID {get; set;}
    public Chef? Cook {get; set;}
}

Week2/ChefsNDishes/Models/MyContext.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace ChefsNDishes.Models;

public class MyContext : DbContext
{  
    public MyContext(DbContextOptions options) : base(options) { }    
    public DbSet<Dish> Dishes { get; set; }
    public DbSet<Chef> Chefs { get; set; }
}

Week2/ChefsNDishes/Controllers/ChefController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using ChefsNDishes.Models;

namespace ChefsDishes.Controllers;

public class ChefController : Controller
{
    private readonly ILogger<ChefController> _logger;

    private MyContext _context;

    public ChefController(ILogger<ChefController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

    [HttpGet("")]
    public IActionResult ViewChefs()
    {
        List<Chef> Cooks = _context.Chefs.Include(c => c.AllDishes).ToList();
        return View(Cooks);
    }

    [HttpGet("Chefs/New")]
    public IActionResult NewChef()
    {
        return View();
    }

    [HttpPost("Chefs/Write")]
    public IActionResult WriteChef(Chef newChef)
    {
        if(ModelState.IsValid)
        {
            _context.Add(newChef);
            _context.SaveChanges();
            return RedirectToAction("ViewChefs");
        }
        return View("NewChef", newChef);
    }
}

Week2/ChefsNDishes/Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ChefsNDishes.Models;
using Microsoft.EntityFrameworkCore;

namespace ChefsNDishes.Controllers;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;

    private MyContext _context;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        _context = context;
    }

    [HttpGet("Dishes/View")]
    public IActionResult ViewDishes()
    {
        List<Dish> dishes = _context.Dishes.Include(dish => dish.Cook).ToList();
        return View(dishes);
    }

    [HttpGet("Dishes/New")]
    public IActionResult NewDish()
    {
        List<Chef> cooks = _context.Chefs.ToList();
        ViewBag.CookList = new SelectList(cooks, "ChefID", "FirstName");
        return View();
    }

    [HttpPost("Dishes/Write")]
    public IActionResult WriteDish(Dish newModel)
    {
        if(ModelState.IsValid)
        {
            // Grab Chef ID
            int CookID = newModel.ChefID;
            // Assigns Dish to Chef/Cook
            newModel.Cook = _context.Chefs.FirstOrDefault(chef => chef.ChefID == CookID);
            // write & save changes
            _context.Add(newModel);
            _context.SaveChanges();
            return RedirectToAction("ViewDishes");
        }
        return View("AddDish", newModel);
    }
}

Week2/ChefsNDishes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChefsNDishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChefsNDishes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Chef" asp-action="ViewChefs">Chefs</a>
                <a class="navbar-brand" asp-area="" asp-controller="Dish" asp-action="ViewDishes">Dishes</a>
                <a class="navbar-brand" asp-area="" asp-controller="Chef" asp-action="NewChef">Add a Chef</a>
                <a class="navbar-brand" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>